#!/usr/bin/env bash

# This file is part of ELNBuildSync
# Copyright (C) 2023-2026 Stephen Gallagher <sgallagh@redhat.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: 	GPL-3.0-or-later

# Created by argbash-init v2.11.0
# ARG_OPTIONAL_SINGLE([log-level],[],[Log verbosity],[INFO])
# ARG_OPTIONAL_SINGLE([db-pw-file],[],[Database password file],[tests/etc/secrets/ebs_db_pw])
# ARG_OPTIONAL_SINGLE([smtp-pw-file],[],[SMTP password file],[tests/etc/secrets/ebs_smtp_pw])
# ARG_OPTIONAL_SINGLE([openid-client-secret-file],[],[OIDC client secret file],[tests/etc/secrets/ebs_oidc_client_secret])
# ARG_OPTIONAL_SINGLE([openid-ca-file],[],[OIDC CA certificate file],[])
# ARG_OPTIONAL_SINGLE([lull-time],[],[Time to wait after the last trigger before starting the batch],[5])
# ARG_OPTIONAL_SINGLE([static-config-file],[],[Static configuration file],[tests/etc/static-config/elnbuildsync.yaml])
# ARG_OPTIONAL_SINGLE([dynamic-config-file],[],[Dynamic configuration file],[tests/etc/dynamic-config/elnbuildsync_dynamic.yaml])
# ARG_OPTIONAL_SINGLE([environment],[],[Environment],[stg])
# ARG_OPTIONAL_SINGLE([krb5-keytab-file],[],[Kerberos keytab for in-process TGT acquisition (optional)])
# ARG_OPTIONAL_SINGLE([krb5-keytab-principal],[],[Kerberos principal for keytab-based TGT acquisition only (default: guessed from static configuration)])
# ARG_OPTIONAL_BOOLEAN([persistent-db],[],[Use persistent database],[off])
# ARG_OPTIONAL_SINGLE([persistent-db-volume],[],[Volume name for persistent database],[ebs_test_pgdata])
# ARG_OPTIONAL_BOOLEAN([build-container],[],[Build the ELNBuildSync container],[off])
# ARG_POSITIONAL_DOUBLEDASH([])
# ARG_POSITIONAL_INF([custom],[Additional arguments to pass to the ELNBuildSync daemon])
# ARG_HELP([],[Run the ELNBuildSync daemon for testing])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='h'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_custom=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_log_level="INFO"
_arg_db_pw_file="tests/etc/secrets/ebs_db_pw"
_arg_smtp_pw_file="tests/etc/secrets/ebs_smtp_pw"
_arg_openid_client_secret_file="tests/etc/secrets/ebs_oidc_client_secret"
_arg_openid_ca_file=
_arg_lull_time="5"
_arg_static_config_file="tests/etc/static-config/elnbuildsync.yaml"
_arg_dynamic_config_file="tests/etc/dynamic-config/elnbuildsync_dynamic.yaml"
_arg_environment="stg"
_arg_krb5_keytab_file=
_arg_krb5_keytab_principal=
_arg_persistent_db="off"
_arg_persistent_db_volume="ebs_test_pgdata"
_arg_build_container="off"


print_help()
{
	printf 'Usage: %s [--log-level <arg>] [--db-pw-file <arg>] [--smtp-pw-file <arg>] [--openid-client-secret-file <arg>] [--openid-ca-file <arg>] [--lull-time <arg>] [--static-config-file <arg>] [--dynamic-config-file <arg>] [--environment <arg>] [--krb5-keytab-file <arg>] [--krb5-keytab-principal <arg>] [--(no-)persistent-db] [--persistent-db-volume <arg>] [--(no-)build-container] [-h|--help] [--] [<custom-1>] ... [<custom-n>] ...\n' "$0"
	printf '\t%s\n' "<custom>: Additional arguments to pass to the ELNBuildSync daemon"
	printf '\t%s\n' "--log-level: Log verbosity (default: 'INFO')"
	printf '\t%s\n' "--db-pw-file: Database password file (default: 'tests/etc/secrets/ebs_db_pw')"
	printf '\t%s\n' "--smtp-pw-file: SMTP password file (default: 'tests/etc/secrets/ebs_smtp_pw')"
	printf '\t%s\n' "--openid-client-secret-file: OIDC client secret file (default: 'tests/etc/secrets/ebs_oidc_client_secret')"
	printf '\t%s\n' "--openid-ca-file: OIDC CA certificate file (no default)"
	printf '\t%s\n' "--lull-time: Time to wait after the last trigger before starting the batch (default: '5')"
	printf '\t%s\n' "--static-config-file: Static configuration file (default: 'tests/etc/static-config/elnbuildsync.yaml')"
	printf '\t%s\n' "--dynamic-config-file: Dynamic configuration file (default: 'tests/etc/dynamic-config/elnbuildsync_dynamic.yaml')"
	printf '\t%s\n' "--environment: Environment (default: 'stg')"
	printf '\t%s\n' "--krb5-keytab-file: Kerberos keytab for in-process TGT acquisition (optional; otherwise use host KCM / existing ccache)"
	printf '\t%s\n' "--krb5-keytab-principal: Principal for keytab-based TGT acquisition only (default: guessed from static configuration when a keytab is set)"
	printf '\t%s\n' "--persistent-db, --no-persistent-db: Use persistent database (off by default)"
	printf '\t%s\n' "--persistent-db-volume: Volume name for persistent database (default: 'ebs_test_pgdata')"
	printf '\t%s\n' "--build-container, --no-build-container: Build the ELNBuildSync container (off by default)"
	printf '\t%s\n' "-h, --help: Prints help"
	printf '\n%s\n' "Run the ELNBuildSync daemon for testing"
}


parse_commandline()
{
	_positionals_count=0
	local _key
	while test $# -gt 0
	do
		_key="$1"
		if test "$_key" = '--'
		then
			shift
			test $# -gt 0 || break
			_positionals+=("$@")
			_positionals_count=$((_positionals_count + $#))
			shift $(($# - 1))
			_last_positional="$1"
			break
		fi
		case "$_key" in
			--log-level)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_log_level="$2"
				shift
				;;
			--log-level=*)
				_arg_log_level="${_key##--log-level=}"
				;;
			--db-pw-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_db_pw_file="$2"
				shift
				;;
			--db-pw-file=*)
				_arg_db_pw_file="${_key##--db-pw-file=}"
				;;
			--smtp-pw-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_smtp_pw_file="$2"
				shift
				;;
			--smtp-pw-file=*)
				_arg_smtp_pw_file="${_key##--smtp-pw-file=}"
				;;
			--openid-client-secret-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_openid_client_secret_file="$2"
				shift
				;;
			--openid-client-secret-file=*)
				_arg_openid_client_secret_file="${_key##--openid-client-secret-file=}"
				;;
			--openid-ca-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_openid_ca_file="$2"
				shift
				;;
			--openid-ca-file=*)
				_arg_openid_ca_file="${_key##--openid-ca-file=}"
				;;
			--lull-time)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_lull_time="$2"
				shift
				;;
			--lull-time=*)
				_arg_lull_time="${_key##--lull-time=}"
				;;
			--static-config-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_static_config_file="$2"
				shift
				;;
			--static-config-file=*)
				_arg_static_config_file="${_key##--static-config-file=}"
				;;
			--dynamic-config-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_dynamic_config_file="$2"
				shift
				;;
			--dynamic-config-file=*)
				_arg_dynamic_config_file="${_key##--dynamic-config-file=}"
				;;
			--environment)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_environment="$2"
				shift
				;;
			--environment=*)
				_arg_environment="${_key##--environment=}"
				;;
			--krb5-keytab-file)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_krb5_keytab_file="$2"
				shift
				;;
			--krb5-keytab-file=*)
				_arg_krb5_keytab_file="${_key##--krb5-keytab-file=}"
				;;
			--krb5-keytab-principal)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_krb5_keytab_principal="$2"
				shift
				;;
			--krb5-keytab-principal=*)
				_arg_krb5_keytab_principal="${_key##--krb5-keytab-principal=}"
				;;
			--no-persistent-db|--persistent-db)
				_arg_persistent_db="on"
				test "${1:0:5}" = "--no-" && _arg_persistent_db="off"
				;;
			--persistent-db-volume)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_persistent_db_volume="$2"
				shift
				;;
			--persistent-db-volume=*)
				_arg_persistent_db_volume="${_key##--persistent-db-volume=}"
				;;
			--no-build-container|--build-container)
				_arg_build_container="on"
				test "${1:0:5}" = "--no-" && _arg_build_container="off"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names=""
	_our_args=$((${#_positionals[@]} - 0))
	for ((ii = 0; ii < _our_args; ii++))
	do
		_positional_names="$_positional_names _arg_custom[$((ii + 0))]"
	done

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJ_DIR=$SCRIPT_DIR/..
POSTGRES_VERSION=18

if [ -r /run/.containerenv ]; then
  CONTAINER_ENGINE=/usr/bin/podman-remote
else
  CONTAINER_ENGINE=/usr/bin/podman
fi

if [ "$_arg_build_container" == "on" ]; then
    # Build the ELNBuildSync container
    ${CONTAINER_ENGINE} build -t localhost/elnbuildsync:local_test_daemon $PROJ_DIR
fi

# Check that pg_isready is available
if ! command -v pg_isready &> /dev/null; then
    echo "pg_isready could not be found, install the 'postgresql' package"
    exit 1
fi

function check_db_avail() {
    PGPASSWORD=$(cat "${_arg_db_pw_file}") \
    pg_isready --quiet \
               --dbname elnbuildsync \
               --username elnbuildsync \
               --host localhost \
               --port 5432
    db_ready=$?
}

function closedb() {
    echo "Terminating database"
    ${CONTAINER_ENGINE} stop temp_postgres
}

# Prepare the container network
${CONTAINER_ENGINE} network create --ignore ebs_local_test

# Check if there's already a database running so we don't start another one
check_db_avail > /dev/null 2>&1

if [ $db_ready -ne 0 ]; then
    # Start a database for testing
    echo -n "Starting up database container "

	if [ "$_arg_persistent_db" == "on" ]; then
		echo "using persistent database volume: ${_arg_persistent_db_volume}"
		PERSISTENT_DB_ARG=(--volume "${_arg_persistent_db_volume}:/var/lib/postgresql")
	else
		echo "using non-persistent database"
		PERSISTENT_DB_ARG=()
	fi
    ${CONTAINER_ENGINE} pull docker.io/postgres:$POSTGRES_VERSION
    ${CONTAINER_ENGINE} run --rm --detach \
		--publish 5432:5432 \
	    --network ebs_local_test \
        --volume ${SCRIPT_DIR}/etc/secrets:/run/secrets:Z \
        --name temp_postgres \
        --env POSTGRES_PASSWORD_FILE=/run/secrets/ebs_db_pw \
        --env POSTGRES_USER=elnbuildsync \
        "${PERSISTENT_DB_ARG[@]}" \
        docker.io/postgres:$POSTGRES_VERSION
    trap closedb EXIT

    echo Started database container, waiting for it to complete initialization

    # Wait for the DB to start up
    db_ready=-1
    while [ $db_ready -ne 0 ]; do
        sleep 0.1
        check_db_avail
    done
fi

if [ "$_arg_environment" == "stg" ]; then
    export FEDORA_MESSAGING_CONF="$SCRIPT_DIR/fedora-messaging/fedora.stg.toml"
else
    export FEDORA_MESSAGING_CONF="$SCRIPT_DIR/fedora-messaging/fedora.toml"
fi

DEFAULT_STATIC_CONFIG_FILE="tests/etc/static-config/elnbuildsync.yaml"
DEFAULT_DYNAMIC_CONFIG_FILE="tests/etc/dynamic-config/elnbuildsync_dynamic.yaml"
DEFAULT_OIDC_CLIENT_SECRET_FILE="tests/etc/secrets/ebs_oidc_client_secret"
CONTAINER_STATIC_CONFIG="/etc/elnbuildsync/static-config/simpletest_elnbuildsync.yaml"
CONTAINER_DYNAMIC_CONFIG="/etc/elnbuildsync/dynamic-config/elnbuildsync_dynamic.yaml"
CONTAINER_OIDC_CLIENT_SECRET="/etc/elnbuildsync/secrets/ebs_oidc_client_secret"
CUSTOM_MOUNT_ARGS=()

if [ "${_arg_openid_client_secret_file}" != "${DEFAULT_OIDC_CLIENT_SECRET_FILE}" ]; then
    CONTAINER_OIDC_CLIENT_SECRET="/etc/elnbuildsync/custom/ebs_oidc_client_secret"
    CUSTOM_MOUNT_ARGS+=(--volume "$(realpath "${_arg_openid_client_secret_file}"):${CONTAINER_OIDC_CLIENT_SECRET}:ro,Z")
fi

OPENID_CA_CONTAINER_ARG=()
if [ -n "${_arg_openid_ca_file}" ]; then
    CONTAINER_OPENID_CA_FILE="/etc/elnbuildsync/custom/openid_ca.pem"
    CUSTOM_MOUNT_ARGS+=(--volume "$(realpath "${_arg_openid_ca_file}"):${CONTAINER_OPENID_CA_FILE}:ro,Z")
    OPENID_CA_CONTAINER_ARG=(--openid-ca-file "${CONTAINER_OPENID_CA_FILE}")
fi

if [ "${_arg_static_config_file}" != "${DEFAULT_STATIC_CONFIG_FILE}" ]; then
    CONTAINER_STATIC_CONFIG="/etc/elnbuildsync/custom/static.yaml"
    CUSTOM_MOUNT_ARGS+=(--volume "$(realpath "${_arg_static_config_file}"):${CONTAINER_STATIC_CONFIG}:ro,Z")
fi

if [ "${_arg_dynamic_config_file}" != "${DEFAULT_DYNAMIC_CONFIG_FILE}" ]; then
    CONTAINER_DYNAMIC_CONFIG="/etc/elnbuildsync/custom/dynamic.yaml"
    CUSTOM_MOUNT_ARGS+=(--volume "$(realpath "${_arg_dynamic_config_file}"):${CONTAINER_DYNAMIC_CONFIG}:ro,Z")
fi

KRB5_CONTAINER_ARG=()
if [ -n "${_arg_krb5_keytab_principal}" ] && [ -z "${_arg_krb5_keytab_file}" ]; then
    die "--krb5-keytab-principal requires --krb5-keytab-file" 1
fi
if [ -n "${_arg_krb5_keytab_file}" ]; then
    CONTAINER_KRB5_KEYTAB_FILE="/etc/elnbuildsync/custom/krb5.keytab"
    CUSTOM_MOUNT_ARGS+=(--volume "$(realpath "${_arg_krb5_keytab_file}"):${CONTAINER_KRB5_KEYTAB_FILE}:ro,Z")
    KRB5_CONTAINER_ARG+=(--krb5-keytab-file "${CONTAINER_KRB5_KEYTAB_FILE}")
fi
if [ -n "${_arg_krb5_keytab_principal}" ]; then
    KRB5_CONTAINER_ARG+=(--krb5-keytab-principal "${_arg_krb5_keytab_principal}")
fi

${CONTAINER_ENGINE} run --rm --interactive --tty \
    --name ebs_test \
	--publish 8080:8080 \
    --network ebs_local_test \
	--userns=keep-id \
	--user "$(id -u):$(id -g)" \
	--security-opt label=disable \
	--env KRB5CCNAME=KCM: \
	--volume "/var/run/.heim_org.h5l.kcm-socket:/var/run/.heim_org.h5l.kcm-socket" \
	--volume "${SCRIPT_DIR}/etc:/etc/elnbuildsync:Z" \
	--volume "${SCRIPT_DIR}/fedora-messaging:/etc/fedora-messaging:Z" \
	"${CUSTOM_MOUNT_ARGS[@]}" \
	--volume "${PROJ_DIR}:/tmp:Z" \
	localhost/elnbuildsync:local_test_daemon \
	--log-level "$_arg_log_level" \
	--static-config-file "${CONTAINER_STATIC_CONFIG}" \
	--dynamic-config-file "${CONTAINER_DYNAMIC_CONFIG}" \
	--lull-time "$_arg_lull_time" \
	--openid-client-secret-file "${CONTAINER_OIDC_CLIENT_SECRET}" \
	"${OPENID_CA_CONTAINER_ARG[@]}" \
	"${KRB5_CONTAINER_ARG[@]}" \
	"${_arg_custom[@]}" \
	2>&1 | tee /tmp/elnbuildsync.log

# ] <-- needed because of Argbash
