# This file is part of ELNBuildSync
# Copyright (C) 2023-2026 Stephen Gallagher <sgallagh@redhat.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SPDX-License-Identifier: 	GPL-3.0-or-later

from __future__ import annotations

import asyncio
import logging

from cachetools import LRUCache, cached
from cachetools.keys import hashkey

from .. import config, kojihelpers
from .connection import call_koji

logger = logging.getLogger(__name__)


class SideTagError(Exception):
    """
    A base class for errors related to side tags.
    """


class SideTagTimeoutError(SideTagError):
    """
    A timeout error related to side tags.
    """


class SideTag:
    """
    A class representing a Koji side tag.
    """

    name: str = None

    def __init__(self, base_tag: str, initial_build_ids: list[int | str] | None = None):
        """
        Initialize the SideTag object.

        :params list initial_build_ids: The list of build IDs to tag into the
        side tag during creation.
        """
        self.base_tag = base_tag
        self.initial_build_ids = initial_build_ids

        # The name of the side-tag is generated by Koji and will be set later
        self.name = None

        # Maps build ID/NVR -> tagging task ID (as returned by tag_builds()).
        # Populated during side-tag preparation and cleared once builds are
        # tagged. cancel_tasks() is given the task ID values on failure.
        self._tagging_tasks_index = {}

    @classmethod
    async def create(
        cls, base_tag: str, initial_build_ids: list[int | str] | None = None
    ) -> SideTag:
        """
        Create a new SideTag object.

        :params str base_tag: The build tag to inherit from (e.g. f39-build)
        :params list initial_build_ids: The list of build IDs to tag into the
        side tag during creation.
        """
        side_tag = cls(base_tag, initial_build_ids)
        await side_tag._prepare()
        return side_tag

    async def _prepare(self):
        """
        Prepare the SideTag object for use. It creates the side tag in Koji,
        tags the initial builds into it, and waits for them to appear in the
        tag.
        """

        build_ids_to_tag = []
        if self.initial_build_ids is not None:
            build_ids_to_tag.extend(self.initial_build_ids)

        # Trigger the creation of the side-tag
        logger.info(f"Creating side tag from {self.base_tag}")
        side_tag_info = await call_koji("createSideTag", self.base_tag)
        self.name = side_tag_info["name"]

        logger.debug(f"Side {self.name} created.")

        if build_ids_to_tag:
            # Convert builds to nvrs to make logging easier
            buildinfos = await kojihelpers.builds.get_multi_buildinfo(build_ids_to_tag)
            nvrs = [buildinfo["nvr"] for buildinfo in buildinfos.values()]

            # Tag the builds
            self._tagging_tasks_index = await tag_builds(self.name, nvrs)

            # Wait for the builds to appear in the tag
            results = await wait_for_nvrs_in_tag(self.name, nvrs)

            if any(not success for success, _ in results):
                # If any of the builds failed to tag, cancel the tagging tasks,
                # remove the partial side-tag, and raise from the first exception.

                exc = next((val for success, val in results if not success), None)

                # Cancel all of the tagging tasks. Even if they completed
                # already, this should be safe to do, and we want to be sure.
                await kojihelpers.builds.cancel_tasks(
                    list(self._tagging_tasks_index.values())
                )

                # Drop the partially created side-tag before propagating.
                await self.remove()

                # Check if the exception is a TimeoutError
                if isinstance(exc, asyncio.TimeoutError):
                    raise SideTagTimeoutError(
                        "Failed to tag builds into side tag"
                    ) from exc
                else:
                    raise SideTagError("Failed to tag builds into side tag") from exc

            # All the builds were tagged successfully, so log them
            for _, value in results:
                logger.info(f"Build {value} tagged into {self.name}")

            # Clear the tagging tasks index
            self._tagging_tasks_index = {}

    async def remove(self):
        """
        Remove the side tag.
        """
        await call_koji("removeSideTag", self.name)
        logger.info(f"Removed side tag {self.name}")


async def tag_builds(tag, build_ids):
    """
    Tag a list of builds into a tag.

    :params str tag: The tag name to tag into
    :params list build_ids: The list of nvrs or build IDs to tag
    :return dict: A dictionary of build_id/NVR -> tagging task_id
    """
    task_index = await call_koji(_tag_builds_thread, tag, build_ids)
    logger.debug(f"Tagged {len(build_ids)} builds into {tag}")

    return task_index


def _tag_builds_thread(bsys, tag, build_ids):
    """
    Tag a list of nvrs into a tag.

    :params str tag: The tag name to tag into
    :params list build_ids: The list of nvrs or build IDs to tag
    :return dict: A dictionary of build_id/NVR -> tagging task_id
    """
    build_vcalls = {}

    try:
        with bsys.multicall(batch=config.koji_batch) as mc:
            logger.info(f"Tagging {len(build_ids)} builds into {tag}")
            for build_id in build_ids:
                build_vcalls[build_id] = mc.tagBuild(tag, build_id)
    except Exception:
        logger.exception("Unexpected error tagging builds into %s", tag)
        raise

    task_index = {}
    for build_id, vcall in build_vcalls.items():
        task_id = vcall.result
        task_index[build_id] = task_id
        logger.info(f"Tagging build {build_id} into {tag} via task {task_id}")

    return task_index


async def untag_builds(tag, builds):
    await call_koji(_untag_builds_thread, tag, builds)
    logger.debug(f"Untagged {len(builds)} builds from {tag}")


def _untag_builds_thread(bsys, tag, build_ids):
    with bsys.multicall(batch=config.koji_batch) as mc:
        logger.info(f"Untagging {len(build_ids)} builds from {tag}")
        for build_id in build_ids:
            mc.untagBuild(tag, build_id, strict=False)


async def get_tags_for_target(target):
    """
    Returns: buildroot_tag, destination_tag
    """

    buildroot_tag, destination_tag = await call_koji(
        _get_tags_for_target_thread, target
    )

    return buildroot_tag, destination_tag


@cached(cache=LRUCache(maxsize=4), key=lambda bsys, target: hashkey(target))
def _get_tags_for_target_thread(bsys, target):
    targetinfo = bsys.getBuildTarget(target)
    logger.debug(f"Target info: {targetinfo}")
    return targetinfo["build_tag_name"], targetinfo["dest_tag_name"]


async def wait_for_nvrs_in_tag(tag, nvrs):
    """
    Wait for a list of nvrs to appear in a tag.

    :params str tag: The tag name to wait for
    :params list nvrs: The list of nvrs to wait for
    :return list: A list of (success, value) results. On failure, ``value`` is
        the underlying exception (e.g. asyncio.TimeoutError), so callers can
        isinstance-check timeout errors directly.
    """
    # Imported lazily to avoid a circular import with listener/batching.
    from .. import listener

    logger.info(f"Waiting for {len(nvrs)} nvrs to appear in tag {tag}")

    results = await asyncio.gather(
        *(
            listener.wait_for_nvr_tag(tag, nvr, timeout=config.tag_timeout)
            for nvr in nvrs
        ),
        return_exceptions=True,
    )
    return [(not isinstance(result, BaseException), result) for result in results]


async def get_nvrs_from_tag(tag):
    """
    Get the list of builds tagged into a tag.

    :params str tag: The tag name to get builds from
    :return dict: A dictionary of nvr -> buildinfo
    """
    builds = await call_koji("listTagged", tag, latest=False, inherit=True)
    return {build["nvr"]: build for build in builds}
